//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace viajes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class foro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public foro()
        {
            this.foro_content = new HashSet<foro_content>();
        }
    
        public decimal id { get; set; }
        public string titulo { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public string propietario { get; set; }
        public string descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<foro_content> foro_content { get; set; }
    }
}
