//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace viajes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class foro_content
    {
        public decimal sub_id { get; set; }
        public decimal id { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public string comentario { get; set; }
        public string usuario { get; set; }
    
        public virtual foro foro { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
