//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace viajes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public string email { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string epassword { get; set; }
        public string token { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
        public Nullable<System.DateTime> fechaBaja { get; set; }
        public int tipoUsuario { get; set; }
        public Nullable<bool> emailVerificado { get; set; }
        public string imaPerfil { get; set; }
        public Nullable<System.DateTime> ultimaConexion { get; set; }
        public string descripcion { get; set; }
    }
}
